"""Route registry helpers for serve workspace management."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

import yaml

GENERATED_HEADER = """# Generated by `autocleaneeg-pipeline serve route`.
# Edit files in routes/ and run `autocleaneeg-pipeline serve route sync`.

"""

_ROUTE_SPEC_KEYS = (
    "id",
    "modes",
    "enabled",
    "archived",
    "priority",
    "taskfile",
    "montage",
    "version",
    "ingestion_folders",
    "ingestion_excludes",
    "file_globs",
    "recursive",
    "sentinel_ext",
    "automation_root",
    "workspace_name",
)

_COMPILED_ROUTE_KEYS = (
    "id",
    "enabled",
    "priority",
    "taskfile",
    "montage",
    "version",
    "ingestion_folders",
    "ingestion_excludes",
    "file_globs",
    "recursive",
    "sentinel_ext",
    "automation_root",
    "workspace_name",
)

_LEGACY_TOP_LEVEL_ROUTE_KEYS = {
    "taskfile",
    "montage",
    "version",
    "ingestion_folders",
    "ingestion_excludes",
    "file_glob",
    "file_globs",
    "sentinel_ext",
    "recursive",
    "automation_root",
    "workspace_name",
    "enabled",
    "priority",
}


def normalize_route_id(value: str) -> str:
    """Return a filesystem-safe route id."""
    cleaned = value.strip().replace(" ", "-")
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    cleaned = cleaned.strip("-_")
    if not cleaned:
        raise ValueError("Route id cannot be empty")
    return cleaned


def routes_dir(workspace_dir: Path) -> Path:
    """Return the route registry directory."""
    return workspace_dir / "routes"


def ensure_routes_dir(workspace_dir: Path) -> Path:
    """Create the route registry directory if needed."""
    directory = routes_dir(workspace_dir)
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def route_spec_path(workspace_dir: Path, route_id: str) -> Path:
    """Return the YAML path for a route spec."""
    return routes_dir(workspace_dir) / f"{normalize_route_id(route_id)}.yaml"


def _atomic_write_text(path: Path, payload: str) -> None:
    tmp_path = path.parent / f"{path.name}.tmp"
    tmp_path.write_text(payload, encoding="utf-8")
    tmp_path.replace(path)


def _load_yaml_mapping(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(path)
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise ValueError(f"YAML file must be a mapping: {path}")
    return data


def _normalize_modes(value: Any) -> list[str]:
    if value is None:
        return ["test"]
    if isinstance(value, str):
        items = [value]
    elif isinstance(value, list) and all(isinstance(item, str) for item in value):
        items = value
    else:
        raise ValueError("modes must be a string or list of strings")

    normalized: list[str] = []
    for item in items:
        if item not in ("test", "live"):
            raise ValueError(f"Unsupported mode: {item}")
        if item not in normalized:
            normalized.append(item)
    if not normalized:
        raise ValueError("modes must not be empty")
    return normalized


def _clean_route_spec(route_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    spec = dict(payload)
    spec["id"] = normalize_route_id(route_id)
    spec["modes"] = _normalize_modes(spec.get("modes"))
    archived = bool(spec.get("archived", False))

    for key in ("taskfile", "montage"):
        if not spec.get(key):
            raise ValueError(f"Route {route_id} missing required field: {key}")
    if not spec.get("ingestion_folders"):
        raise ValueError(f"Route {route_id} missing required field: ingestion_folders")
    if archived:
        spec["enabled"] = False

    cleaned: dict[str, Any] = {}
    for key in _ROUTE_SPEC_KEYS:
        if key not in spec:
            continue
        value = spec[key]
        if value is None:
            continue
        if key == "archived" and value is False:
            continue
        if key in ("ingestion_excludes", "file_globs") and value == []:
            continue
        cleaned[key] = value
    return cleaned


def load_route_specs(workspace_dir: Path) -> list[dict[str, Any]]:
    """Load all route specs in deterministic order."""
    directory = routes_dir(workspace_dir)
    if not directory.exists():
        return []

    specs: list[dict[str, Any]] = []
    for path in sorted(directory.glob("*.yaml")):
        data = _load_yaml_mapping(path)
        route_id = str(data.get("id") or path.stem)
        spec = _clean_route_spec(route_id, data)
        specs.append(spec)
    specs.sort(key=lambda item: (-int(item.get("priority", 0)), str(item["id"])))
    return specs


def upsert_route_spec(
    workspace_dir: Path, route_id: str, updates: dict[str, Any]
) -> tuple[Path, dict[str, Any], str]:
    """Create or update a route spec atomically."""
    normalized_id = normalize_route_id(route_id)
    ensure_routes_dir(workspace_dir)
    path = route_spec_path(workspace_dir, normalized_id)

    existing: dict[str, Any] = {}
    if path.exists():
        existing = _load_yaml_mapping(path)

    merged = dict(existing)
    merged["id"] = normalized_id
    for key, value in updates.items():
        if key not in _ROUTE_SPEC_KEYS:
            raise ValueError(f"Unsupported route field: {key}")
        merged[key] = value

    if "modes" not in merged:
        merged["modes"] = ["test"]

    cleaned = _clean_route_spec(normalized_id, merged)
    payload = yaml.safe_dump(cleaned, sort_keys=False, allow_unicode=False)

    status = "created"
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == payload:
            return path, cleaned, "unchanged"
        status = "updated"

    _atomic_write_text(path, payload)
    return path, cleaned, status


def promote_route_spec(workspace_dir: Path, route_id: str) -> tuple[Path, dict[str, Any], str]:
    """Add live mode to an existing route spec."""
    path = route_spec_path(workspace_dir, route_id)
    if not path.exists():
        raise FileNotFoundError(f"Route not found: {normalize_route_id(route_id)}")
    spec = _load_yaml_mapping(path)
    modes = _normalize_modes(spec.get("modes"))
    if "live" not in modes:
        modes.append("live")
    return upsert_route_spec(workspace_dir, route_id, {"modes": modes})


def set_route_archived(
    workspace_dir: Path, route_id: str, archived: bool
) -> tuple[Path, dict[str, Any], str]:
    """Archive or unarchive an existing route spec."""
    path = route_spec_path(workspace_dir, route_id)
    if not path.exists():
        raise FileNotFoundError(f"Route not found: {normalize_route_id(route_id)}")
    updates: dict[str, Any] = {"archived": archived}
    if archived:
        updates["enabled"] = False
    return upsert_route_spec(workspace_dir, route_id, updates)


def archive_route_spec(workspace_dir: Path, route_id: str) -> tuple[Path, dict[str, Any], str]:
    """Archive an existing route spec."""
    return set_route_archived(workspace_dir, route_id, True)


def unarchive_route_spec(
    workspace_dir: Path, route_id: str
) -> tuple[Path, dict[str, Any], str]:
    """Unarchive an existing route spec."""
    return set_route_archived(workspace_dir, route_id, False)


def _compiled_route(route: dict[str, Any]) -> dict[str, Any]:
    compiled: dict[str, Any] = {}
    for key in _COMPILED_ROUTE_KEYS:
        if key not in route:
            continue
        compiled[key] = route[key]
    return compiled


def _route_modes(route: dict[str, Any]) -> list[str]:
    return _normalize_modes(route.get("modes"))


def _render_compiled_config(base_config: dict[str, Any], mode: str, routes: Iterable[dict[str, Any]]) -> str:
    compiled: dict[str, Any] = {}
    for key, value in base_config.items():
        if key in _LEGACY_TOP_LEVEL_ROUTE_KEYS or key == "automations":
            continue
        compiled[key] = value
    compiled["mode"] = mode
    compiled["automation_mode"] = True
    compiled["automations"] = [_compiled_route(route) for route in routes]
    return GENERATED_HEADER + yaml.safe_dump(
        compiled,
        sort_keys=False,
        allow_unicode=False,
    )


def sync_route_registry(
    workspace_dir: Path, *, modes: Iterable[str] = ("test", "live")
) -> dict[str, dict[str, Any]]:
    """Compile route specs back into serve-test.yaml and serve-live.yaml."""
    route_specs = load_route_specs(workspace_dir)
    results: dict[str, dict[str, Any]] = {}

    for mode in modes:
        config_path = workspace_dir / f"serve-{mode}.yaml"
        base_config = _load_yaml_mapping(config_path)
        selected = [
            route
            for route in route_specs
            if not route.get("archived", False) and mode in _route_modes(route)
        ]
        payload = _render_compiled_config(base_config, mode, selected)
        changed = True
        if config_path.exists():
            changed = config_path.read_text(encoding="utf-8") != payload
        if changed:
            _atomic_write_text(config_path, payload)
        results[mode] = {
            "path": config_path,
            "changed": changed,
            "route_count": len(selected),
        }

    return results
