[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:redis]
command=redis-server --appendonly yes --dir /workspace
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis.log

[program:api]
command=autocleaneeg-pipeline serve api --path /workspace --mode %(ENV_MODE)s --port 4000 --host 0.0.0.0
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/supervisor/api.log
stderr_logfile=/var/log/supervisor/api.log

[program:worker1]
command=autocleaneeg-pipeline serve worker --path /workspace --mode %(ENV_MODE)s
autostart=true
autorestart=true
startsecs=15
stdout_logfile=/var/log/supervisor/worker1.log
stderr_logfile=/var/log/supervisor/worker1.log

[program:worker2]
command=autocleaneeg-pipeline serve worker --path /workspace --mode %(ENV_MODE)s
autostart=true
autorestart=true
startsecs=15
stdout_logfile=/var/log/supervisor/worker2.log
stderr_logfile=/var/log/supervisor/worker2.log
