"""User-facing caveats for template-based EEG source localization."""

from __future__ import annotations

from pathlib import Path
from typing import Any

SOURCE_LOCALIZATION_UNITS = "native_source_units"
SOURCE_LOCALIZATION_TEMPLATE = "fsaverage"
SOURCE_LOCALIZATION_ATLAS = "Desikan-Killiany (aparc), 68 ROI channels"

SOURCE_LOCALIZATION_SHORT_NOTE = (
    "Source-localized ROI signals are template-based estimates, not scalp microvolts "
    "or unique anatomical truth. Interpret them as native source units with limited "
    "spatial resolution, template-anatomy uncertainty, inverse-solution spread, ROI "
    "averaging, and possible polarity/sign ambiguity."
)

_SOURCE_LOCALIZATION_CAVEATS = [
    "EEG source localization is an inverse estimate; multiple source patterns can explain the same scalp data.",
    "This block uses template anatomy (`fsaverage`), so individual anatomy and electrode placement are approximate.",
    "Low-density EEG and montage quality limit spatial resolution, especially for deep or nearby sources.",
    "Minimum-norm estimates are spatially smooth and can spread activity across adjacent cortical regions.",
    "Outputs are 68 Desikan-Killiany ROI time courses in native source units, not scalp microvolts.",
    "ROI averaging can obscure within-region variation, and ROI polarity/sign can be ambiguous.",
    "Use source-localized results as descriptive/supporting evidence unless validated with subject-specific anatomy or converging methods.",
]


def source_localization_report_notes() -> list[str]:
    """Return concise notes suitable for the run report."""
    return [SOURCE_LOCALIZATION_SHORT_NOTE]


def source_localization_caveats() -> list[str]:
    """Return detailed caveats for output documentation."""
    return list(_SOURCE_LOCALIZATION_CAVEATS)


def source_localization_readme_text(params: dict[str, Any]) -> str:
    """Build the README written beside source-localization outputs."""
    method = params.get("method", "MNE")
    lambda2 = params.get("lambda2", "unknown")
    montage = params.get("montage", "unknown")
    template = params.get("template", SOURCE_LOCALIZATION_TEMPLATE)
    atlas = params.get("atlas", SOURCE_LOCALIZATION_ATLAS)
    units = params.get("units", SOURCE_LOCALIZATION_UNITS)

    caveats = "\n".join(f"- {item}" for item in source_localization_caveats())
    return f"""# Source Localization Output Notes

These files were generated by AutoClean EEG source localization.

## Method Parameters

- Method: `{method}`
- Lambda2: `{lambda2}`
- Montage: `{montage}`
- Template anatomy: `{template}`
- Atlas/output space: `{atlas}`
- Output units: `{units}`

## Interpretation Caveats

{caveats}

## Practical Guidance

Report these outputs as template-based ROI source estimates. Avoid describing them as precise anatomical localization or as scalp-voltage data. For claims requiring anatomical precision, validate with subject-specific MRI/electrode models or converging evidence.
"""


def write_source_localization_readme(
    output_dir: str | Path, params: dict[str, Any]
) -> Path:
    """Write source_localization_README.md beside source outputs."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    readme_path = output_path / "source_localization_README.md"
    readme_path.write_text(source_localization_readme_text(params), encoding="utf-8")
    return readme_path
